<a href="https://colab.research.google.com/github/ksavcoder-17/Holiday_package_purchase_prediction/blob/main/Random_forest_regressor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Used car price prediction**
## 1. Problem Statement:

*   This dataset comprises used cars sold on cardekho.comn in india as well as important features of these cars.
*   if user can predict the car price based on input features.

*   Prediction results can be used to give new seller the price suggestion based on the market condition.


## 2. Data collection:
The data is collected from cardekho.com website.These data contains information about used car.
#
#
#

##### **Data Description (Feature Information)**
*  **car_name**: Car's Full name, which includes brand and specific model name.
*  **brand**: Brand Name of the particular car.
model: Exact model name of the car of a particular brand.

*  **seller_type**: Which Type of seller is selling the used car.

*  **fuel_type**: Fuel used in the used car, which was put up on sale.

*   **transmission_type**: Transmission used in the used car, which was put on sale.
*   **vehicle_age**: The count of years since car was bought.


*  **mileage**: It is the number of kilometer the car runs per litre.

*  **engine**: It is the engine capacity in cc(cubic centimeters)

*  **max_power**: Max power it produces in BHP.

*   **seats**: Total number of seats in car.

*   **selling_price**: The sale price which was put up on website.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
from six.moves import urllib

warnings.filterwarnings("ignore")

%matplotlib inline

In [2]:
##Load Dataset:
df = pd.read_csv('/content/used_car_price.csv',index_col=[0])

In [3]:
df.head(5)

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

## Data Description:

In [4]:
print(df.shape)
print(df.info())
df.describe()

(15411, 13)
<class 'pandas.core.frame.DataFrame'>
Index: 15411 entries, 0 to 19543
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15411 non-null  object
 1   brand              15411 non-null  object
 2   model              15411 non-null  object
 3   vehicle_age        15411 non-null  int64
 4   km_driven          15411 non-null  int64
 5   seller_type        15411 non-null  object
 6   fuel_type          15411 non-null  object
 7   transmission_type  15411 non-null  object
 8   mileage            15411 non-null  float64
 9   engine             15411 non-null  int64
 10  max_power          15411 non-null  float64
 11  seats              15411 non-null  int64
 12  selling_price      15411 non-null  int64
dtypes: float64(2), int64(5), object(6)
memory usage: 1.6+ MB
None

,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price
count,15411.000000,1.541100e+04,15411.000000,15411.000000,15411.000000,15411.000000,1.541100e+04
mean,6.036338,5.561648e+04,19.701151,1486.057751,100.588254,5.325482,7.749711e+05
std,3.013291,5.161855e+04,4.171265,521.106696,42.972979,0.807628,8.941284e+05
min,0.000000,1.000000e+02,4.000000,793.000000,38.400000,0.000000,4.000000e+04
25%,4.000000,3.000000e+04,17.000000,1197.000000,74.000000,5.000000,3.850000e+05
50%,6.000000,5.000000e+04,19.670000,1248.000000,88.500000,5.000000,5.560000e+05
75%,8.000000,7.000000e+04,22.700000,1582.000000,117.300000,5.000000,8.250000e+05
max,29.000000,3.800000e+06,33.540000,6592.000000,626.000000,9.000000,3.950000e+07

In [5]:
total = df.isnull().sum().sort_values(ascending=False)

In [6]:
df.count()

car_name             15411
brand                15411
model                15411
vehicle_age          15411
km_driven            15411
seller_type          15411
fuel_type            15411
transmission_type    15411
mileage              15411
engine               15411
max_power            15411
seats                15411
selling_price        15411
dtype: int64

In [7]:
## Percentage of null value in each feature:
percent = ((df.isnull().sum()/df.isnull().count())*100).sort_values(ascending=False)
pd.concat([total,percent],axis=1,keys=['Total','Percent'])

                   Total  Percent
car_name               0      0.0
brand                  0      0.0
model                  0      0.0
vehicle_age            0      0.0
km_driven              0      0.0
seller_type            0      0.0
fuel_type              0      0.0
transmission_type      0      0.0
mileage                0      0.0
engine                 0      0.0
max_power              0      0.0
seats                  0      0.0
selling_price          0      0.0

In [8]:
print('Summary Statistics of numerical features for DataFrame are as follows:')
print('-'*100)
df.describe()

Summary Statistics of numerical features for DataFrame are as follows:
----------------------------------------------------------------------------------------------------

,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price
count,15411.000000,1.541100e+04,15411.000000,15411.000000,15411.000000,15411.000000,1.541100e+04
mean,6.036338,5.561648e+04,19.701151,1486.057751,100.588254,5.325482,7.749711e+05
std,3.013291,5.161855e+04,4.171265,521.106696,42.972979,0.807628,8.941284e+05
min,0.000000,1.000000e+02,4.000000,793.000000,38.400000,0.000000,4.000000e+04
25%,4.000000,3.000000e+04,17.000000,1197.000000,74.000000,5.000000,3.850000e+05
50%,6.000000,5.000000e+04,19.670000,1248.000000,88.500000,5.000000,5.560000e+05
75%,8.000000,7.000000e+04,22.700000,1582.000000,117.300000,5.000000,8.250000e+05
max,29.000000,3.800000e+06,33.540000,6592.000000,626.000000,9.000000,3.950000e+07

# **Data Cleaning**
####  **Handling missing values:**


*  Handling missing values
*   Handling duplicate values
*   Check datatype
*   Understand the dataset

In [9]:
# check the null values
## check the features with naan value
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [10]:
# remove unnecessary features:
df.drop('car_name', axis=1, inplace = True)
df.drop('brand',axis=1, inplace=True)

In [11]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [12]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [13]:
from IPython.core.interactiveshell import dis
## Finding numerical and cateforical features in dataset :
num_features = [feature for feature in df.columns if df[feature].dtypes!='O']
cat_features = [ feature for feature in df.columns if df[feature].dtypes == 'O']
discrete_features = [feature for feature in num_features if len(df[feature].unique())<=25]
continuous_features = [ feature for feature in num_features if feature not in discrete_features]
print('There are {} numerical features {}'.format(len(num_features),num_features))
print('\nThere are {} Categorical features {}'.format(len(cat_features),cat_features))
print('\nThere are {} Discrete features {}'.format(len(discrete_features),discrete_features))
print('\nThere are {} Continuous features {}'.format(len(continuous_features),continuous_features))

There are 7 numerical features ['vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats', 'selling_price']

There are 4 Categorical features ['model', 'seller_type', 'fuel_type', 'transmission_type']

There are 2 Discrete features ['vehicle_age', 'seats']

There are 5 Continuous features ['km_driven', 'mileage', 'engine', 'max_power', 'selling_price']

In [14]:
# Independent and Dependent features:
from sklearn.model_selection import train_test_split
X = df.drop(['selling_price'],axis=1)
y= df['selling_price']

In [15]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

# **Feature Encoding and Scaling**
#### **One Hot Encoding for columns which had lesser unique values and not ordinal**

*   One Hot encoding is a process by which categorical variables are converted into a form that could be provided to ML algorithms to do a better job in prediction.

In [16]:
len(df['model'].unique())

120

In [17]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X['model']=le.fit_transform(X['model'])

In [18]:
len(df['seller_type'].unique()),len(df['fuel_type'].unique()),len(df['transmission_type'].unique())

(3, 5, 2)

In [19]:
# create column transformer with 3 types of transformers:
num_features =X.select_dtypes(exclude='object').columns
onehot_columns =['seller_type','fuel_type','transmission_type']
label_encoder_columns =['model']

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer =StandardScaler()
oh_transformer =OneHotEncoder(drop='first')
preprocessor = ColumnTransformer(
    [
        ('OneHotEncoder',oh_transformer,onehot_columns),
        ('StandardScaler',numeric_transformer,num_features)
    ],remainder = 'passthrough'
)

In [20]:
X=preprocessor.fit_transform(X)

In [21]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [22]:
#seperate dataset into train and test:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape,X_test.shape

((12328, 14), (3083, 14))

# **Model Training and Model Selection**

In [23]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score, mean_absolute_error,mean_squared_error

In [24]:
## Create a function to evaluate model
def evaluate_model(true, predicted):
  mae=mean_absolute_error(true,predicted)
  mse = mean_squared_error(true,predicted)
  rmse=np.sqrt(mse)
  r2_square = r2_score(true,predicted)
  return mae,rmse,r2_square

In [25]:
## Beggining Model Training:
models = { 'Linear Regression':LinearRegression(),
          'Lasso':Lasso(),
           'Ridge':Ridge(),
           'K-Neighbors Regressor':KNeighborsRegressor(),
           'Decision Tree': DecisionTreeRegressor(),
           'Random Forest Regressor': RandomForestRegressor()
           }
for i in range(len(list(models))):
  model=list(models.values())[i]
  model.fit(X_train,y_train) # Train Model
  ## Make Prediction:
  y_train_pred = model.predict(X_train)
  y_test_pred = model.predict(X_test)

  ## Evaluate Train and Test Dataset:
  model_train_mae, model_train_rmse,model_train_r2 = evaluate_model(y_train,y_train_pred)
  model_test_mae, model_test_rmse,model_test_r2 = evaluate_model(y_test,y_test_pred)
  print(list(models.keys())[i])

  print("<--------Model Performance for Train dataset-------->")
  print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
  print('- Mean Absolute Error: {:.4f}'.format(model_train_mae))
  print('- R2_Score {:.4f}'.format(model_train_r2))

  print("<--------Model Performance for Test dataset-------->")
  print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
  print('- Mean Absolute Error: {:.4f}'.format(model_test_mae))
  print('- R2_Score {:.4f}'.format(model_test_r2))

  print("="*65)
  print('\n')

Linear Regression
<--------Model Performance for Train dataset-------->
- Root Mean Squared Error: 553855.6665
- Mean Absolute Error: 268101.6071
- R2_Score 0.6218
<--------Model Performance for Test dataset-------->
- Root Mean Squared Error: 502543.5930
- Mean Absolute Error: 279618.5794
- R2_Score 0.6645
=================================================================


Lasso
<--------Model Performance for Train dataset-------->
- Root Mean Squared Error: 553855.6710
- Mean Absolute Error: 268099.2226
- R2_Score 0.6218
<--------Model Performance for Test dataset-------->
- Root Mean Squared Error: 502542.6696
- Mean Absolute Error: 279614.7461
- R2_Score 0.6645
=================================================================


Ridge
<--------Model Performance for Train dataset-------->
- Root Mean Squared Error: 553856.3160
- Mean Absolute Error: 268059.8015
- R2_Score 0.6218
<--------Model Performance for Test dataset-------->
- Root Mean Squared Error: 502533.8230
- Mean Absolute Error: 279557.2169
- R2_Score 0.6645
=================================================================


K-Neighbors Regressor
<--------Model Performance for Train dataset-------->
- Root Mean Squared Error: 325885.9831
- Mean Absolute Error: 91430.9701
- R2_Score 0.8691
<--------Model Performance for Test dataset-------->
- Root Mean Squared Error: 253071.9428
- Mean Absolute Error: 112672.8917
- R2_Score 0.9149
=================================================================


Decision Tree
<--------Model Performance for Train dataset-------->
- Root Mean Squared Error: 20797.2352
- Mean Absolute Error: 5164.8199
- R2_Score 0.9995
<--------Model Performance for Test dataset-------->
- Root Mean Squared Error: 304938.0920
- Mean Absolute Error: 123896.3861
- R2_Score 0.8765
=================================================================


Random Forest Regressor
<--------Model Performance for Train dataset-------->
- Root Mean Squared Error: 141657.6985
- Mean Absolute Error: 39901.2337
- R2_Score 0.9753
<--------Model Performance for Test dataset-------->
- Root Mean Squared Error: 223573.8877
- Mean Absolute Error: 100851.7913
- R2_Score 0.9336
=================================================================

In [26]:
## Initialize few parameters for Hyperparameter tunning:
knn_params = {'n_neighbors':[2,3,10,20,40,50]}
rf_params = {'max_depth':[5,8,15,None,10],
             "max_features":[5,7,"auto",8],
             "min_samples_split":[2,8,15,20],
             "n_estimators":[100,200,500,1000]}

In [27]:
# Models list for Hyperparmater tunning:
randomcv_models =[('KNN',KNeighborsRegressor(),knn_params),
                  ('RF',RandomForestRegressor(),rf_params)
                  ]

In [28]:
## Hyperparameter tunning:
from sklearn.model_selection import RandomizedSearchCV
model_param = {}
for name, model, params in randomcv_models:
  random = RandomizedSearchCV(estimator = model,
                              param_distributions =params,
                              n_iter =100,
                              cv = 3,
                              verbose =2,
                              n_jobs =-1)
  random.fit(X_train,y_train)
  model_param[name]=random.best_params_

for model_name in model_param:
  print(f"-----------Best Params {model_name}---------")
  print(model_param[model_name])

Fitting 3 folds for each of 6 candidates, totalling 18 fits
Fitting 3 folds for each of 100 candidates, totalling 300 fits
-----------Best Params KNN---------
{'n_neighbors': 10}
-----------Best Params RF---------
{'n_estimators': 1000, 'min_samples_split': 2, 'max_features': 5, 'max_depth': None}

In [34]:
## Retrainning models with best parameters :
models = {
           'K-Neighbors Regressor':KNeighborsRegressor(n_neighbors= 10,n_jobs=-1),
           'Random Forest Regressor': RandomForestRegressor(n_estimators= 1000, min_samples_split= 2, max_features= 5, max_depth= None)
           }
for i in range(len(list(models))):
  model=list(models.values())[i]
  model.fit(X_train,y_train) # Train Model
  ## Make Prediction:
  y_train_pred = model.predict(X_train)
  y_test_pred = model.predict(X_test)

  ## Evaluate Train and Test Dataset:
  model_train_mae, model_train_rmse,model_train_r2 = evaluate_model(y_train,y_train_pred)
  model_test_mae, model_test_rmse,model_test_r2 = evaluate_model(y_test,y_test_pred)
  print(list(models.keys())[i])

  print("<--------Model Performance for Train dataset-------->")
  print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
  print('- Mean Absolute Error: {:.4f}'.format(model_train_mae))
  print('- R2_Score {:.4f}'.format(model_train_r2))

  print("<--------Model Performance for Test dataset-------->")
  print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
  print('- Mean Absolute Error: {:.4f}'.format(model_test_mae))
  print('- R2_Score {:.4f}'.format(model_test_r2))

  print("="*65)
  print('\n')

K-Neighbors Regressor
<--------Model Performance for Train dataset-------->
- Root Mean Squared Error: 363465.6927
- Mean Absolute Error: 103489.6090
- R2_Score 0.8371
<--------Model Performance for Test dataset-------->
- Root Mean Squared Error: 263849.8119
- Mean Absolute Error: 117481.4548
- R2_Score 0.9075
=================================================================


Random Forest Regressor
<--------Model Performance for Train dataset-------->
- Root Mean Squared Error: 127658.2264
- Mean Absolute Error: 38942.9588
- R2_Score 0.9799
<--------Model Performance for Test dataset-------->
- Root Mean Squared Error: 207903.1925
- Mean Absolute Error: 97992.9275
- R2_Score 0.9426
=================================================================